# Sunucu Ayarları
server.port=8081
spring.application.name=main-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Veritabanı (PostgreSQL) Ayarları
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/encoder_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ve Hibernate (ORM) Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dosya Yükleme Sınırları
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

# FFmpeg Klasör Yolları
encoder.folder.input=/video_test/input
encoder.folder.output=/video_test/output
encoder.folder.clips=/video_test/clips
encoder.folder.live=/video_test/live_output/live
encoder.folder.live-clips=/video_test/live_output/live_clips
encoder.folder.assets=/video_test/assets

# Zamanlanmış Görev (Cron Job) Ayarları - (Yöneticinin İstediği 1 Dakika Ayarı)
encoding.cron.expression=0 */1 * * * *