server:
  port: 8081
spring:
  application:
    name: encoder # Projenin adı

  # Veritabanı (PostgreSQL) Ayarları
  datasource:
    url: jdbc:postgresql://localhost:5432/encoder_db # 'encoder_db' yerine kendi oluşturduğun veritabanı adını yaz
    username: postgres # PostgreSQL kurulumunda belirlediğin kullanıcı adı (genelde postgres'tir)
    password: aslan2088 # PostgreSQL kurulumunda belirlediğin şifre
    driver-class-name: org.postgresql.Driver

  # JPA ve Hibernate (ORM) Ayarları
  jpa:
    hibernate:
      ddl-auto: update # Geliştirme aşamasında tabloları otomatik günceller
    show-sql: true # Arka planda çalışan SQL komutlarını konsolda gösterir (öğrenmek için çok faydalıdır)
    properties:
      hibernate:
        format_sql: true # Konsoldaki SQL'leri okunabilir hale getirir

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

encoder:
  folder:
    input: C:/video_test/input
    output: C:/video_test/output
