# Bu işçinin portu (Main servisimiz genelde 8080 olur, bunu 8081 yapıyoruz)
server.port=8083

# Sistemin adı (Eureka'da bu isimle görünecek)
spring.application.name=encoder-service

# Eureka Rehberinin Adresi (Oraya gidip kayıt olması için)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Veritabanı Bağlantısı (Main servis ile aynı veritabanına bağlanmalı)
spring.datasource.url=jdbc:postgresql://localhost:5432/encoder_db
spring.datasource.username=postgres
spring.datasource.password=aslan2088
spring.jpa.hibernate.ddl-auto=update

encoder.folder.output=/video_test/output