# Eureka'nın varsayılan portu
server.port=8761

# Sistemin adı
spring.application.name=eureka-server

# Sunucu olduğu için kendini kaydetmesini engelliyoruz
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false